# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 603ec0928fea2f0cf47561771d08a065eb6a522db7425104243c5673253f19c7c89323410b1f81a2a149f749d619ff5c1a0c437e374ba11efd917025bc997405

test:
  secret_key_base: aa2fa9d63f6f1c1cdf40d301dffa43545d8b270e7515c4e600776a74481904d8a9941a921d8b40a71d0d3af5e87c92976470ed0fca45af7055903e45b2030061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
